name: 'Docker Build Action'
description: 'Build a docker image and push to Quay.io'
inputs:
  context:
    required: true
    default: .
  repository_server:
    required: true
  repository_name:
    required: true
  repository_username:
    required: true
  repository_password:
    required: true
  docker_tag:
    required: true
  docker_cache_tag:
    required: true
  docker_args:
    required: false
  dockerfile:
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.context }}
    - ${{ inputs.dockerfile }}
    - ${{ inputs.repository_server }}
    - ${{ inputs.repository_name }}
    - ${{ inputs.repository_username }}
    - ${{ inputs.repository_password }}
    - ${{ inputs.docker_tag }}
    - ${{ inputs.docker_cache_tag }}
    - ${{ inputs.docker_args }}
